import { WeatherCondition, WeatherItem } from './models/weather-item';

export const WEATHER_ITEMS: WeatherItem[] = [
  {
    id: 1,
    title: 'Kyiv Morning Forecast',
    description: 'Cool spring morning with clear sky and comfortable visibility throughout the city.',
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=80',
    temperature: 12,
    forecastDate: new Date('2026-03-28T09:00:00'),
    condition: WeatherCondition.Sunny,
    tags: ['spring', 'clear sky', 'morning'],
    location: {
      city: 'Kyiv',
      country: 'Ukraine',
      coordinates: { lat: 50.4501, lon: 30.5234 },
    },
    details: {
      humidity: 58,
      windSpeed: 3.4,
      pressure: 1018,
    },
    isDiscount: true,
    quantity: 7,
    isFeatured: false,
  },
  {
    id: 2,
    title: 'Lviv Afternoon Forecast',
    description: 'Partly cloudy weather with light wind and stable atmospheric pressure.',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80',
    temperature: 15,
    forecastDate: new Date('2026-03-29T15:30:00'),
    condition: WeatherCondition.Cloudy,
    tags: ['afternoon', 'clouds', 'city walk'],
    location: {
      city: 'Lviv',
      country: 'Ukraine',
      coordinates: { lat: 49.8397, lon: 24.0297 },
    },
    details: {
      humidity: 64,
      windSpeed: 4.1,
      pressure: 1013,
    },
    isDiscount: false,
    quantity: 4,
    isFeatured: true,
  },
  {
    id: 3,
    title: 'Odesa Sea Breeze',
    description: 'Warm day near the coast with fresh breeze and higher humidity.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',
    temperature: 18,
    forecastDate: new Date('2026-03-30T12:00:00'),
    condition: WeatherCondition.Sunny,
    tags: ['sea', 'breeze', 'warm'],
    location: {
      city: 'Odesa',
      country: 'Ukraine',
      coordinates: { lat: 46.4825, lon: 30.7233 },
    },
    details: {
      humidity: 70,
      windSpeed: 6.3,
      pressure: 1011,
    },
    isDiscount: true,
    quantity: 10,
    isFeatured: true,
  },
  {
    id: 4,
    title: 'Kharkiv Evening Rain',
    description: 'Moderate rain is expected in the evening, so an umbrella will be useful.',
    imageUrl: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=900&q=80',
    temperature: 9,
    forecastDate: new Date('2026-03-31T19:00:00'),
    condition: WeatherCondition.Rainy,
    tags: ['rain', 'evening', 'umbrella'],
    location: {
      city: 'Kharkiv',
      country: 'Ukraine',
      coordinates: { lat: 49.9935, lon: 36.2304 },
    },
    details: {
      humidity: 84,
      windSpeed: 5.8,
      pressure: 1007,
    },
    isDiscount: false,
    quantity: 0,
    isFeatured: false,
  },
  {
    id: 5,
    title: 'Dnipro Wind Alert',
    description: 'Strong wind and dense clouds are expected during the day.',
    imageUrl: 'https://images.unsplash.com/photo-1499346030926-9a72daac6c63?auto=format&fit=crop&w=900&q=80',
    temperature: 11,
    forecastDate: new Date('2026-04-01T13:00:00'),
    condition: WeatherCondition.Stormy,
    tags: ['windy', 'alert', 'cloudy'],
    location: {
      city: 'Dnipro',
      country: 'Ukraine',
      coordinates: { lat: 48.4647, lon: 35.0462 },
    },
    details: undefined, // штучно прибрали вкладений об'єкт для демонстрації Safe Navigation
    isDiscount: false,
    quantity: 2,
    isFeatured: true,
  },
  {
    id: 6,
    title: 'Bukovel Snow Forecast',
    description: 'Cold mountain weather with snow showers and low temperatures.',
    imageUrl: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d?auto=format&fit=crop&w=900&q=80',
    temperature: -3,
    forecastDate: new Date('2026-04-02T08:00:00'),
    condition: WeatherCondition.Snowy,
    tags: ['mountains', 'snow', 'cold'],
    location: {
      city: 'Bukovel',
      country: 'Ukraine',
      coordinates: { lat: 48.3537, lon: 24.4162 },
    },
    details: {
      humidity: 88,
      windSpeed: 7.9,
      pressure: 1009,
    },
    isDiscount: true,
    quantity: 0,
    isFeatured: false,
  },
];